/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import listeners.FrmLoginListener;

/**
 *
 * @author consc
 */
public class FrmHome extends javax.swing.JFrame {

    private FrmLoginListener frmListerner;
    /**
     * Creates new form home
     */
    public FrmHome() {
        this.frmListerner = new FrmLoginListener(this);
        initComponents();        
        frmListerner.fillFrmListCombosFrmHome();
        frmListerner.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comBoxCityArea = new javax.swing.JComboBox<>();
        comBoxPropertyType = new javax.swing.JComboBox<>();
        comBoxStructure = new javax.swing.JComboBox<>();
        comBoxFurniture = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        menuMain = new javax.swing.JMenuBar();
        menuRent = new javax.swing.JMenu();
        menuSale = new javax.swing.JMenu();
        menuListPpty = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenu();
        menuContact = new javax.swing.JMenuItem();
        menuCareers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Property Listing!");

        comBoxCityArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Area of City" }));
        comBoxCityArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxCityAreaActionPerformed(evt);
            }
        });

        comBoxPropertyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Property Type" }));

        comBoxStructure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Structure" }));

        comBoxFurniture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Furniture" }));

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Structure", "Type", "Price", "Address", "Area", "Furniture", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMain);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 210, Short.MAX_VALUE)
                        .addComponent(comBoxCityArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBoxPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBoxStructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBoxFurniture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comBoxCityArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxStructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxFurniture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuMain.setRequestFocusEnabled(false);

        menuRent.setText("RENT");
        menuRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRentActionPerformed(evt);
            }
        });
        menuMain.add(menuRent);

        menuSale.setText("SALE");
        menuMain.add(menuSale);

        menuListPpty.setText("LIST YOUR PROPERTY");
        menuMain.add(menuListPpty);

        menuInfo.setText("INFO");

        menuContact.setText("Contact us");
        menuContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContactActionPerformed(evt);
            }
        });
        menuInfo.add(menuContact);

        menuCareers.setText("Careers");
        menuCareers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCareersActionPerformed(evt);
            }
        });
        menuInfo.add(menuCareers);

        menuMain.add(menuInfo);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCareersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCareersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCareersActionPerformed

    private void comBoxCityAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCityAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCityAreaActionPerformed

    private void menuRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRentActionPerformed
        // TODO add your handling code here:
        new FrmList().setVisible(true);
    }//GEN-LAST:event_menuRentActionPerformed

    private void menuContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHome().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> comBoxCityArea;
    private javax.swing.JComboBox<Object> comBoxFurniture;
    private javax.swing.JComboBox<Object> comBoxPropertyType;
    private javax.swing.JComboBox<Object> comBoxStructure;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuCareers;
    private javax.swing.JMenuItem menuContact;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuListPpty;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuRent;
    private javax.swing.JMenu menuSale;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables

    public  javax.swing.JTable getTblMain() {
        return this.tblMain;
    }

    public javax.swing.JComboBox<Object> getComBoxCityArea() {
        return comBoxCityArea;
    }

    public void setComBoxCityArea(javax.swing.JComboBox<Object> comBoxCityArea) {
        this.comBoxCityArea = comBoxCityArea;
    }

    public javax.swing.JComboBox<Object> getComBoxFurniture() {
        return comBoxFurniture;
    }

    public void setComBoxFurniture(javax.swing.JComboBox<Object> comBoxFurniture) {
        this.comBoxFurniture = comBoxFurniture;
    }

    public javax.swing.JComboBox<Object> getComBoxPropertyType() {
        return comBoxPropertyType;
    }

    public void setComBoxPropertyType(javax.swing.JComboBox<Object> comBoxPropertyType) {
        this.comBoxPropertyType = comBoxPropertyType;
    }

    public javax.swing.JComboBox<Object> getComBoxStructure() {
        return comBoxStructure;
    }

    public void setComBoxStructure(javax.swing.JComboBox<Object> comBoxStructure) {
        this.comBoxStructure = comBoxStructure;
    }
    
}
