/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JComboBox;
import listeners.FrmLoginListener;

/**
 *
 * @author consc
 */
public class FrmList extends javax.swing.JFrame {

    public JComboBox getComboCustomer() {
        return comboCustomer;
    }

    /**
     * Creates new form FrmList
     */
    public FrmList() {
        initComponents();
        new FrmLoginListener(this).fillFrmListCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNameOfProperty = new javax.swing.JTextPane();
        lblNameOfProperty = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPrice = new javax.swing.JTextPane();
        lblPrice = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextPane();
        lblDescription = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comBoxPropertyType = new javax.swing.JComboBox();
        lblPropertyType = new javax.swing.JLabel();
        comBoxCityArea = new javax.swing.JComboBox();
        lblCityArea = new javax.swing.JLabel();
        comBoxStructure = new javax.swing.JComboBox();
        lblStructure = new javax.swing.JLabel();
        lblFurniture = new javax.swing.JLabel();
        comBoxFurniture = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboCustomer = new javax.swing.JComboBox();
        menuMain = new javax.swing.JMenuBar();
        menuRent = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuListPpty = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenu();
        menuContact = new javax.swing.JMenuItem();
        menuCareers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("List your Property! ");

        jScrollPane1.setViewportView(txtNameOfProperty);

        lblNameOfProperty.setText("Name of Property");

        lblAddress.setText("Address");

        jScrollPane2.setViewportView(txtAddress);

        jScrollPane3.setViewportView(txtPrice);

        lblPrice.setText("Price");

        lblArea.setText("Area");

        jScrollPane4.setViewportView(txtArea);

        lblDescription.setText("Description");

        txtAreaDescription.setColumns(20);
        txtAreaDescription.setRows(5);
        jScrollPane5.setViewportView(txtAreaDescription);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        comBoxPropertyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxPropertyTypeActionPerformed(evt);
            }
        });

        lblPropertyType.setText("Property Type");

        lblCityArea.setText("City Area");

        lblStructure.setText("Structure");

        lblFurniture.setText("Furniture");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter details of a new property");

        jLabel2.setText("Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameOfProperty)
                            .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPropertyType)
                            .addComponent(lblCityArea)
                            .addComponent(lblStructure))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comBoxPropertyType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comBoxCityArea, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comBoxStructure, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFurniture, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comBoxFurniture, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btnSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(172, 172, 172))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDescription)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameOfProperty)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPropertyType)
                        .addComponent(comBoxPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comBoxCityArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCityArea)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice)
                    .addComponent(lblStructure)
                    .addComponent(comBoxStructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFurniture)
                        .addComponent(comBoxFurniture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuMain.setRequestFocusEnabled(false);

        menuRent.setText("Edit Property");
        menuRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRentActionPerformed(evt);
            }
        });
        menuMain.add(menuRent);

        jMenu1.setText("Add Client");
        menuMain.add(jMenu1);

        menuListPpty.setText("DashBoard");
        menuMain.add(menuListPpty);

        menuInfo.setText("INFO");

        menuContact.setText("Contact us");
        menuInfo.add(menuContact);

        menuCareers.setText("Careers");
        menuCareers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCareersActionPerformed(evt);
            }
        });
        menuInfo.add(menuCareers);

        menuMain.add(menuInfo);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCareersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCareersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCareersActionPerformed

    private void comBoxPropertyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxPropertyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxPropertyTypeActionPerformed

    private void menuRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRentActionPerformed
        // TODO add your handling code here:
        new FrmList().setVisible(true);
    }//GEN-LAST:event_menuRentActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        new FrmLoginListener(this).resetProperty(evt);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new FrmLoginListener(this).cancelProperty(evt);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        new FrmLoginListener(this).insertProperty(evt);
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comBoxCityArea;
    private javax.swing.JComboBox<String> comBoxFurniture;
    private javax.swing.JComboBox comBoxPropertyType;
    private javax.swing.JComboBox comBoxStructure;
    private javax.swing.JComboBox comboCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCityArea;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFurniture;
    private javax.swing.JLabel lblNameOfProperty;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPropertyType;
    private javax.swing.JLabel lblStructure;
    private javax.swing.JMenuItem menuCareers;
    private javax.swing.JMenuItem menuContact;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuListPpty;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuRent;
    private javax.swing.JTextPane txtAddress;
    private javax.swing.JTextPane txtArea;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextPane txtNameOfProperty;
    private javax.swing.JTextPane txtPrice;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getComBoxCityArea() {
        return comBoxCityArea;
    }

    public void setComBoxCityArea(javax.swing.JComboBox comBoxCityArea) {
        this.comBoxCityArea = comBoxCityArea;
    }

    public javax.swing.JComboBox getComBoxFurniture() {
        return comBoxFurniture;
    }

    public void setComBoxFurniture(javax.swing.JComboBox comBoxFurniture) {
        this.comBoxFurniture = comBoxFurniture;
    }

    public javax.swing.JComboBox getComBoxPropertyType() {
        return comBoxPropertyType;
    }

    public void setComBoxPropertyType(javax.swing.JComboBox comBoxPropertyType) {
        this.comBoxPropertyType = comBoxPropertyType;
    }

    public javax.swing.JComboBox getComBoxStructure() {
        return comBoxStructure;
    }

    public void setComBoxStructure(javax.swing.JComboBox comBoxStructure) {
        this.comBoxStructure = comBoxStructure;
    }

    public javax.swing.JTextPane getTxtAddress() {
        return txtAddress;
    }

    public void setTxtAddress(javax.swing.JTextPane txtAddress) {
        this.txtAddress = txtAddress;
    }

    public javax.swing.JTextPane getTxtArea() {
        return txtArea;
    }

    public void setTxtArea(javax.swing.JTextPane txtArea) {
        this.txtArea = txtArea;
    }

    public javax.swing.JTextArea getTxtAreaDescription() {
        return txtAreaDescription;
    }

    public void setTxtAreaDescription(javax.swing.JTextArea txtAreaDescription) {
        this.txtAreaDescription = txtAreaDescription;
    }

    public javax.swing.JTextPane getTxtNameOfProperty() {
        return txtNameOfProperty;
    }

    public void setTxtNameOfProperty(javax.swing.JTextPane txtNameOfProperty) {
        this.txtNameOfProperty = txtNameOfProperty;
    }

    public javax.swing.JTextPane getTxtPrice() {
        return txtPrice;
    }

    public void setTxtPrice(javax.swing.JTextPane txtPrice) {
        this.txtPrice = txtPrice;
    }
}
