/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import listeners.FrmLoginListener;

/**
 *
 * @author consc
 */
public class FrmDashboardAdmin extends javax.swing.JFrame {

    private FrmLoginListener frmLoginListener;
    /**
     * Creates new form FrmDashboardAdmin
     */
    public FrmDashboardAdmin() {
        this.frmLoginListener =  new FrmLoginListener(this);
        initComponents();
        new FrmLoginListener(this).generateReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblActiveCustomers = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInactiveCustomers = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAgentsActive = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblActiveClients = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPropertyInactive = new javax.swing.JLabel();
        lblAgents1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblClientInactive = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPropertyActive = new javax.swing.JLabel();
        lblHelpDeskActive = new javax.swing.JLabel();
        lblHelpDeskInactive = new javax.swing.JLabel();
        lblAgentAdminActive = new javax.swing.JLabel();
        lblAgentAdminInactive = new javax.swing.JLabel();
        lblAdminActive = new javax.swing.JLabel();
        lblAdminInactive = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblPropertySaleActive = new javax.swing.JLabel();
        lblPropertiesSaleInactive = new javax.swing.JLabel();
        lblAgentsInactive = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jLabel5.setText("jLabel5");

        jLabel14.setText("jLabel14");

        jLabel16.setText("jLabel16");

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        lblActiveCustomers.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel3.setText("Active");

        lblInactiveCustomers.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel6.setText("Inactive");

        lblAgentsActive.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel9.setText("City:");

        lblActiveClients.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel12.setText("City:");

        lblPropertyInactive.setText("jLabel16");

        lblAgents1.setText("Beograd");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Users:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setText("Customers:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel15.setText("Clients:");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel17.setText("Agents:");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setText("HelpDesk:");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel19.setText("Agent Admin:");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel20.setText("Admin:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Properties:");

        lblClientInactive.setText("jLabel2");

        jLabel2.setText("Beograd");

        lblPropertyActive.setText("jLabel10");

        lblHelpDeskActive.setText("jLabel10");

        lblHelpDeskInactive.setText("jLabel13");

        lblAgentAdminActive.setText("jLabel21");

        lblAgentAdminInactive.setText("jLabel23");

        lblAdminActive.setText("jLabel24");

        lblAdminInactive.setText("jLabel25");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setText("Rent:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setText("Sale:");

        jLabel21.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel21.setText("City:");

        jLabel23.setText("Beograd");

        lblPropertySaleActive.setText("jLabel24");

        lblPropertiesSaleInactive.setText("jLabel25");

        lblAgentsInactive.setText("jLabel8");

        jMenu1.setText("Properties");

        jMenuItem4.setText("New Property Detail");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("List of Property");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Users");

        jMenuItem1.setText("Enter Customer Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Enter Clients Details");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Enter Users Details");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel11))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblActiveCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblActiveClients)
                                                    .addComponent(jLabel3)
                                                    .addComponent(lblAgentsActive)
                                                    .addComponent(lblHelpDeskActive)
                                                    .addComponent(lblAgentAdminActive)
                                                    .addComponent(lblAdminActive)
                                                    .addComponent(lblPropertyActive)
                                                    .addComponent(lblPropertySaleActive)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel1)
                                                .addGap(23, 23, 23)))))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblAgents1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2))))
                                .addGap(192, 192, 192)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblInactiveCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClientInactive)
                            .addComponent(lblHelpDeskInactive)
                            .addComponent(lblAgentAdminInactive)
                            .addComponent(lblAdminInactive)
                            .addComponent(lblPropertyInactive)
                            .addComponent(lblPropertiesSaleInactive)
                            .addComponent(jButton1)
                            .addComponent(lblAgentsInactive))))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblActiveCustomers)
                            .addComponent(lblInactiveCustomers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblActiveClients)
                            .addComponent(lblClientInactive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblAgents1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentsActive)
                    .addComponent(lblAgentsInactive))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblHelpDeskActive)
                    .addComponent(lblHelpDeskInactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblAgentAdminActive)
                    .addComponent(lblAgentAdminInactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblAdminActive)
                    .addComponent(lblAdminInactive))
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertyActive)
                    .addComponent(lblPropertyInactive))
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertySaleActive)
                    .addComponent(lblPropertiesSaleInactive))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrmLoginListener(this).cancelAdminDashBoard(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new FrmLoginListener(this).showPropertyForm(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FrmLoginListener(this).showCustomerForm(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FrmLoginListener(this).showClientsForm(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new FrmLoginListener(this).showFormList(evt);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new FrmLoginListener(this).showFormUsers(evt);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDashboardAdmin().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel lblActiveClients;
    private javax.swing.JLabel lblActiveCustomers;
    private javax.swing.JLabel lblAdminActive;
    private javax.swing.JLabel lblAdminInactive;
    private javax.swing.JLabel lblAgentAdminActive;
    private javax.swing.JLabel lblAgentAdminInactive;
    private javax.swing.JLabel lblAgents1;
    private javax.swing.JLabel lblAgentsActive;
    private javax.swing.JLabel lblAgentsInactive;
    private javax.swing.JLabel lblClientInactive;
    private javax.swing.JLabel lblHelpDeskActive;
    private javax.swing.JLabel lblHelpDeskInactive;
    private javax.swing.JLabel lblInactiveCustomers;
    private javax.swing.JLabel lblPropertiesSaleInactive;
    private javax.swing.JLabel lblPropertyActive;
    private javax.swing.JLabel lblPropertyInactive;
    private javax.swing.JLabel lblPropertySaleActive;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblActiveClients() {
        return lblActiveClients;
    }

    public void setLblActiveClients(javax.swing.JLabel lblActiveClients) {
        this.lblActiveClients = lblActiveClients;
    }

    public javax.swing.JLabel getLblActiveCustomers() {
        return lblActiveCustomers;
    }

    public void setLblActiveCustomers(javax.swing.JLabel lblActiveCustomers) {
        this.lblActiveCustomers = lblActiveCustomers;
    }

    public javax.swing.JLabel getLblAdminActive() {
        return lblAdminActive;
    }

    public void setLblAdminActive(javax.swing.JLabel lblAdminActive) {
        this.lblAdminActive = lblAdminActive;
    }

    public javax.swing.JLabel getLblAdminInactive() {
        return lblAdminInactive;
    }

    public void setLblAdminInactive(javax.swing.JLabel lblAdminInactive) {
        this.lblAdminInactive = lblAdminInactive;
    }

    public javax.swing.JLabel getLblAgentAdminActive() {
        return lblAgentAdminActive;
    }

    public void setLblAgentAdminActive(javax.swing.JLabel lblAgentAdminActive) {
        this.lblAgentAdminActive = lblAgentAdminActive;
    }

    public javax.swing.JLabel getLblAgentAdminInactive() {
        return lblAgentAdminInactive;
    }

    public void setLblAgentAdminInactive(javax.swing.JLabel lblAgentAdminInactive) {
        this.lblAgentAdminInactive = lblAgentAdminInactive;
    }

    public javax.swing.JLabel getLblAgents1() {
        return lblAgents1;
    }

    public void setLblAgents1(javax.swing.JLabel lblAgents1) {
        this.lblAgents1 = lblAgents1;
    }

    public javax.swing.JLabel getLblAgentsActive() {
        return lblAgentsActive;
    }

    public void setLblAgentsActive(javax.swing.JLabel lblAgentsActive) {
        this.lblAgentsActive = lblAgentsActive;
    }

    public javax.swing.JLabel getLblAgentsInactive() {
        return lblAgentsInactive;
    }

    public void setLblAgentsInactive(javax.swing.JLabel lblAgentsInactive) {
        this.lblAgentsInactive = lblAgentsInactive;
    }

    public javax.swing.JLabel getLblClientInactive() {
        return lblClientInactive;
    }

    public void setLblClientInactive(javax.swing.JLabel lblClientInactive) {
        this.lblClientInactive = lblClientInactive;
    }

    public javax.swing.JLabel getLblHelpDeskActive() {
        return lblHelpDeskActive;
    }

    public void setLblHelpDeskActive(javax.swing.JLabel lblHelpDeskActive) {
        this.lblHelpDeskActive = lblHelpDeskActive;
    }

    public javax.swing.JLabel getLblHelpDeskInactive() {
        return lblHelpDeskInactive;
    }

    public void setLblHelpDeskInactive(javax.swing.JLabel lblHelpDeskInactive) {
        this.lblHelpDeskInactive = lblHelpDeskInactive;
    }

    public javax.swing.JLabel getLblInactiveCustomers() {
        return lblInactiveCustomers;
    }

    public void setLblInactiveCustomers(javax.swing.JLabel lblInactiveCustomers) {
        this.lblInactiveCustomers = lblInactiveCustomers;
    }

    public javax.swing.JLabel getLblPropertiesSaleInactive() {
        return lblPropertiesSaleInactive;
    }

    public void setLblPropertiesSaleInactive(javax.swing.JLabel lblPropertiesSaleInactive) {
        this.lblPropertiesSaleInactive = lblPropertiesSaleInactive;
    }

    public javax.swing.JLabel getLblPropertyActive() {
        return lblPropertyActive;
    }

    public void setLblPropertyActive(javax.swing.JLabel lblPropertyActive) {
        this.lblPropertyActive = lblPropertyActive;
    }

    public javax.swing.JLabel getLblPropertyInactive() {
        return lblPropertyInactive;
    }

    public void setLblPropertyInactive(javax.swing.JLabel lblPropertyInactive) {
        this.lblPropertyInactive = lblPropertyInactive;
    }

    public javax.swing.JLabel getLblPropertySaleActive() {
        return lblPropertySaleActive;
    }

    public void setLblPropertySaleActive(javax.swing.JLabel lblPropertySaleActive) {
        this.lblPropertySaleActive = lblPropertySaleActive;
    }
}
