/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author consc
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuMain = new javax.swing.JMenuBar();
        menuRent = new javax.swing.JMenu();
        menuSale = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuListPpty = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenu();
        menuContact = new javax.swing.JMenuItem();
        menuCareers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuMain.setRequestFocusEnabled(false);

        menuRent.setText("Add Property ");
        menuMain.add(menuRent);

        menuSale.setText("Edit");
        menuMain.add(menuSale);

        jMenu1.setText("Add Client");
        menuMain.add(jMenu1);

        menuListPpty.setText("DashBoard");
        menuMain.add(menuListPpty);

        menuInfo.setText("INFO");

        menuContact.setText("Contact us");
        menuInfo.add(menuContact);

        menuCareers.setText("Careers");
        menuCareers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCareersActionPerformed(evt);
            }
        });
        menuInfo.add(menuCareers);

        menuMain.add(menuInfo);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCareersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCareersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCareersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem menuCareers;
    private javax.swing.JMenuItem menuContact;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuListPpty;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuRent;
    private javax.swing.JMenu menuSale;
    // End of variables declaration//GEN-END:variables
}
